package com.ohdodok.catchytape.core.domain.model

enum class CtErrorType {
    DUPLICATED_NICKNAME,
    WRONG_TOKEN,
    BAD_REQUEST,
    SERVER,
    CONNECTION,
    IO,
    SSL_HAND_SHAKE,
    UN_KNOWN,
    NOT_EXIST_PLAYLIST_ON_USER,
    NOT_EXIST_MUSIC,
    ALREADY_ADDED,
    INVALID_INPUT_VALUE,
    NOT_EXIST_USER,
    ALREADY_EXIST_EMAIL,
    NOT_EXIST_GENRE,
    EXPIRED_TOKEN,
    SERVICE
}

